### ISSUE TITLE
Adding Transfer History

### ISSUE THREAD

**Issue by meGodDev** [felipeall/transfermarkt-api#25]
Hello, i've been experimenting your api on python for a few days and liked it a lot. found it would be cool to add a Transfer History feature.

**Comment by meGodDev** [comment]
> Hello, i've been experimenting your api on python for a few days and liked it a lot. found it would be cool to add a Transfer History feature.

(so i forgot to add it as a request and it came out as an issue but its ok)

**Comment by felipeall** [comment]
Hello, @meGodDev! Thanks for your feedback, I'm glad that you have been using this API and enjoying it!

Regarding the Transfer History feature, you mean that you would like to retrieve the transfers for a specific **player**, **club** or **league**?

If you mean for a **player**, you can use the endpoint `/players/{player_id}/transfers`, which for example retrieves the following payload for the player_id `28003`:

`
{
  "id": "28003",
  "name": "Messi",
  "history": [
    {
      "transferID": "4418847",
      "transferSeason": "23/24",
      "transferDate": "Jul 15, 2023",
      "oldClubID": "583",
      "oldClubName": "Paris SG",
      "newClubID": "69261",
      "newClubName": "Miami",
      "marketValue": "€35.00m",
      "fee": "free transfer"
    },
    {
      "transferID": "3489998",
      "transferSeason": "21/22",
      "transferDate": "Aug 10, 2021",
      "oldClubID": "131",
      "oldClubName": "Barcelona",
      "newClubID": "583",
      "newClubName": "Paris SG",
      "marketValue": "€80.00m",
      "fee": "free transfer"
    },
    {
      "transferID": "48265",
      "transferSeason": "05/06",
      "transferDate": "Jul 1, 2005",
      "oldClubID": "2464",
      "oldClubName": "Barcelona B",
      "newClubID": "131",
      "newClubName": "Barcelona",
      "marketValue": "€3.00m",
      "fee": "-"
    },
    {
      "transferID": "153557",
      "transferSeason": "03/04",
      "transferDate": "Mar 5, 2004",
      "oldClubID": "63954",
      "oldClubName": "Barcelona C",
      "newClubID": "2464",
      "newClubName": "Barcelona B",
      "marketValue": "-",
      "fee": "-"
    },
    {
      "transferID": "1993882",
      "transferSeason": "03/04",
      "transferDate": "Nov 28, 2003",
      "oldClubID": "2470",
      "oldClubName": "Barça U19",
      "newClubID": "63954",
      "newClubName": "Barcelona C",
      "marketValue": "-",
      "fee": "-"
    },
    {
      "transferID": "1136539",
      "transferSeason": "03/04",
      "transferDate": "Sep 13, 2003",
      "oldClubID": "14321",
      "oldClubName": "Barça U16",
      "newClubID": "2470",
      "newClubName": "Barça U19",
      "marketValue": "-",
      "fee": "-"
    },
    {
      "transferID": "2326361",
      "transferSeason": "02/03",
      "transferDate": "Jul 1, 2002",
      "oldClubID": "70295",
      "oldClubName": "Barça Youth",
      "newClubID": "14321",
      "newClubName": "Barça U16",
      "marketValue": "-",
      "fee": "-"
    },
    {
      "transferID": "181327",
      "transferSeason": "00/01",
      "transferDate": "Jul 1, 2000",
      "oldClubID": "92364",
      "oldClubName": "Newell's Youth",
      "newClubID": "70295",
      "newClubName": "Barça Youth",
      "marketValue": "-",
      "fee": "free transfer"
    }
  ],
  "youthClubs": [
    "Grandoli FC (1992-1995)",
    "Newell's Old Boys (1995-2000)"
  ],
  "lastUpdate": "2023-07-21T16:15:02.089452"
}
`

**Comment by meGodDev** [comment]
Thanks dude! u helped me a lot.

**Comment by felipeall** [comment]
No problem, glad to help! Please let me know if you have any suggestion or feedback 😉

**Comment by meGodDev** [comment]
> No problem, glad to help! Please let me know if you have any suggestion or feedback 😉

Ofc, thank you! Is there any way of receiving a line-up of a certain club?

**Comment by felipeall** [comment]
> > No problem, glad to help! Please let me know if you have any suggestion or feedback 😉
> 
> Ofc, thank you! Is there any way of receiving a line-up of a certain club?

You can use the `/clubs/{club_id}/players` endpoint to get the full **current** squad of a given club (e.g. Barcelona current squad: `/clubs/131/players`)

Also it is possible to retrieve it for a specific season using the `season_id` parameter. (e.g Barcelona 2015 squad: `/clubs/131/players?season_id=2015`)
