### ISSUE TITLE
LaLiga not working

### ISSUE THREAD

**Issue by ITibirna** [felipeall/transfermarkt-api#31]
Curl

curl -X 'GET' \
  'https://transfermarkt-api.vercel.app/competitions/search/LaLiga?page_number=1' \
  -H 'accept: application/json'
Request URL
https://transfermarkt-api.vercel.app/competitions/search/LaLiga?page_number=1
Server response
Code	Details
500
Undocumented
Error: response status is 500

Response body
Download
{
  "error": {
    "code": "500",
    "message": "A server error has occurred"
  }
}

**Comment by ITibirna** [comment]
The same for Champions League

![image](https://github.com/felipeall/transfermarkt-api/assets/32740623/141db1bb-dd84-4f39-b46e-0dafa3bc45e2)

**Comment by felipeall** [comment]
Hello @ITibirna!

Thanks for reporting this issue. It looks like it is a bug in cases where the search returns only one page. I will open a PR to fix it
