### ISSUE TITLE
Add player stats

### ISSUE THREAD

**Issue by DriesDeprest** [felipeall/transfermarkt-api#33]
I saw that you already started the work to create an endpoint to retrieve statistics for a player: https://github.com/felipeall/transfermarkt-api/tree/feature/player-stats

What work still needs to be done to complete this? Do you need any help on this?

**Comment by felipeall** [comment]
Hi @DriesDeprest, thanks for reaching out! Actually the development of the Player Stats endpoint was ready, only the unit tests were missing. I will open a PR to implement this feature right now. Please don't hesitate to contact me if you have any feedback or suggestion for this project 😉
