### ISSUE TITLE
Player Transfer Data not working

### ISSUE THREAD

**Issue by RBrown1985** [felipeall/transfermarkt-api#44]
Hi,

Player transfer data doesn't appear to work. It only seems to show youth clubs information.

Thanks :)

**Comment by felipeall** [comment]
Hi @RBrown1985,

Thanks for opening this issue to report it! This is a similar problem report in #38: the player transfers data is now being retrieved in the client side from a Transfermarkt endpoint that didn't exist until recently. It should be a quick fix, I will open a PR to fix it.

Thank you once again for the report!
