### ISSUE TITLE
players profile endpoint issue

### ISSUE THREAD

**Issue by marcinszewczykArch** [felipeall/transfermarkt-api#58]
Hi!
Thanks a lot for making this project, I have fun playing with your api ;)

It seems there is some issue with `players/{playerId}/profile` and `players/{playerId}/stats` endpoints (response status is 404):
```
 {
  "detail": "Invalid request (url: https://www.transfermarkt.com/-/profil/spieler/1)"
}
```

All the best!

**Comment by marcinszewczykArch** [comment]
Hi @felipeall,
thanks for the quick response. I think I have found the solution for this issue and created the PR. 
Please consider it like a suggestion only, I have no experience with Python and XPath.
However I have tested this locally and it seems to work. 
Regards, Marcin

**Comment by felipeall** [comment]
Hey @marcinszewczykArch, huge thanks for your assistance! I made an adjustment to the URL XPath. Now, it targets an element unique to the player profile, ensuring that an error is triggered if an invalid ID is entered. To verify this, you can run the unit tests using the pytest command. Apologies for not mentioning this in the documentation! 😅
