### ISSUE TITLE
API Swagger doesnt function anymore

### ISSUE THREAD

**Issue by yaschi1879** [felipeall/transfermarkt-api#82]
https://transfermarkt-api.fly.dev/docs
The API doesn't function anymore. The link above is not retrievable

I can't acces the data anymore with the code below:
url = f"https://transfermarkt-api.fly.dev/clubs/{club_id}/profile"
response = requests.get(url)

**Comment by tommhe14** [comment]
+

API down.

**Comment by yaschi1879** [comment]
So what does this mean?

Is this permanently or just temporary?

________________________________
Von: mane ***@***.***>
Gesendet: Montag, 9. Dezember 2024 10:58
An: felipeall/transfermarkt-api ***@***.***>
Cc: Schmid, Yannick ***@***.***>; Author ***@***.***>
Betreff: Re: [felipeall/transfermarkt-api] API Swagger doesnt function anymore (Issue #82)


  *

API down.

**Comment by felipeall** [comment]
It's back online guys

![Alt Text](https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExYm5ienB3ZjhhdDZ0MDMyMnIyM2JlamR3b2RsbjlhamNubTgyODNkMSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/r1IMdmkhUcpzy/giphy.gif)
